### PR TITLE
Add evoMark Inertia Wordpress community adapter

### PR DESCRIPTION
**Pull request by craigrileyuk**
Adds a second community WordPress adapter for Inertia to the list.

### CODE REVIEW

**Comment by reinink** [comment]
Should this maybe just replace the existing boxybird WordPress adapter? It doesn't look updated anymore.

**Comment by craigrileyuk** [comment]
@reinink It could do, I just wasn't my place to remove someone else's adapter.

**Comment by reinink** [comment]
Go ahead 👍👍

**Comment by craigrileyuk** [comment]
@reinink Okay, done

**Comment by reinink** [comment]
Thanks Craig! 👍

**Pull request merged**
