### PR TITLE
Add Mithril.js demo

### PR DESCRIPTION
**Pull request by tbreuss**
Added link to PingCRM on Mithril.js repo.

### CODE REVIEW

**Comment by Juhlinus** [comment]
Hello @tbreuss ! 

I see that you have an adapter for Mithril.js as well. Maybe we should add a link to that to the website as well?

**Comment by tbreuss** [comment]
The adapter is embedded in the PingCRM, since this is my only "test" use case at the moment.

It will come in one or two weeks, when I have separated it into a new repo and made available via NPM.

**Comment by Juhlinus** [comment]
> The adapter is embedded in the PingCRM, since this is my only "test" use case at the moment.
> 
> It will come as stand-alone package in one or two weeks, when I have separated it into a new repo and made available via NPM.
I guess it would be cool for people using Mihtril.js to check out a Ping CRM example. However, wouldn't it be a better learning experience if they also had their hands on the adapter? 
My argument is that people would probably look at the example app in order to get a better understanding as how to use the adapters and Inertia.js itself.
So, maybe we should hold off on adding this until you're finished with the adapter? 😀

**Comment by tbreuss** [comment]
No problem. We can wait until the adapter is ready.

**Comment by tbreuss** [comment]
Here we go. I just finished and released the Mithril.js community adapter. 

Now, this MR contains three changes:

- added link to Mithril.js community adapter
- sorted links alphabetically since we already have seven links now (can revert this back if wished)
- added link to PingCRM on Mithril.js

Hope this is okay.

**Comment by tbreuss** [comment]
@Juhlinus Did you notice my comment?

**Comment by Juhlinus** [comment]
@tbreuss Yup!

@sebastiandedeyne Looks good to merge to me!

**Comment by tbreuss** [comment]
Great, thanks.

**Comment by sebastiandedeyne** [comment]
Awesome, thanks!

**Pull request merged**
