### PR TITLE
Fix import for use `visit` on React

### PR DESCRIPTION
**Pull request by rbngzlv**
Hi,

I think that the import in React docs is wrong, and possibly the others in the same page.

Thanks for the library, looks good!

### CODE REVIEW

**Comment by reinink** [comment]
Yes, it totally is wrong. Thanks for catching this!

**Comment by reinink** [comment]
Hmm, this is actually wrong. 😂 

Should be: `import { Inertia } from '@inertiajs/inertia-react'`

I'll fix it, since I need to do the others anyway. 👍

**Comment by rbngzlv** [comment]
If I use your proposed import `import { Inertia } from '@inertiajs/inertia-react'` I get:

```
Uncaught TypeError: Cannot read property 'visit' of undefined
``` 

I think that `Inertia` is not exported on the `inertia-react` package.

**Comment by reinink** [comment]
Oh frig, you're right. That's the way we used to have it.

FIXING AGAIN 😂 

Thanks for following up @rbngzlv!

**Pull request merged**
