### PR TITLE
Add MasoniteFramework server-side adapter to the list

### PR DESCRIPTION
**Pull request by girardinsamuel**
As discussed in #99 here is the PR 😃

### CODE REVIEW

**Comment by reinink** [comment]
Thanks for sharing. Can you refactor to put this on the new `community-adapters.mdx` page? Thanks!

**Comment by girardinsamuel** [comment]
@reinink Yes, I will do it !

**Comment by girardinsamuel** [comment]
@reinink Should be okay now !

**Comment by reinink** [comment]
Awesome, thanks! 👍

**Pull request merged**
