### PR TITLE
Fix imports on react examples (missing namespace, hook names)

### PR DESCRIPTION
**Pull request by rbngzlv**
Hi! Another round fixing some react imports. :smile:

### CODE REVIEW

**Comment by rbngzlv** [comment]
Wait one moment, don't merge it, please! I'm checking the hook names.

**Comment by rbngzlv** [comment]
Ok, ready to review, fixed the hook name for access page props.

**Comment by reinink** [comment]
Awesome, thanks so much @rbngzlv. 👍

**Comment by rbngzlv** [comment]
You are welcome, thank your for the library!

**Pull request merged**
