### PR TITLE
Update Prettier + add pre-commit hook

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
- Update Prettier config (remove default values)
- Run Prettier on full codebase
- Add pre-commit hook

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@reinink Resolved conflicts

**Comment by reinink** [comment]
Hey @MichaelDeBoey! I'm not a fan of the `proseWrap` option. Frankly, I kind of hate Prettier's line length handling. I really wish that feature could be disabled. I also don't think we need the pre-commit hook. Plus I'm not sure what value we're getting from changing the Prettier config. Maybe you can explain that?

**Comment by MichaelDeBoey** [comment]
Hey @reinink!

The `proseWrap` option makes all the Markdown files still readable when looking at them in your IDE, without having to scroll horizontally.

I just kept the same line-width that was already defined, but removed the values that are the same as the default values Prettier is using (i.e. `tabwidth = 2`).

I've added the pre-commit hook, so everyone who changes the code will commit correctly formatted code.
Right now it's possible to commit code that isn't compliant with the Prettier config, so adding this pre-commit hook prevents that.

**Comment by MichaelDeBoey** [comment]
Ping @reinink

**Comment by claudiodekker** [comment]
Thanks for contributing to our documentation!

Unfortunately, I'm going to delay merging this code for now, given that the documentation was private for quite some time while as they were being rewritten, as well as that they included several SSR-related config details that were sponsors-only at the time. As a result, it's now difficult to judge what's still relevant/up-to-date, and what's no longer relevant, so we're mass-closing older PR's with this message (sorry!)

Feel free to update and re-submit your change if you believe that it's still relevant, at which point we'll reconsider adding this (assuming any previous views discussed in this thread have changed).

Thanks!

**Pull request closed without merging**
