### PR TITLE
Add imports for React and Svelte to documentation

### PR DESCRIPTION
**Pull request by antonnyman**
I'm new to Inertia and have just successfully gotten it to work with React and Rails. 🎉 

I just wanted to add a clarification to the docs to make clear where (and how) you should import the `InertiaLink` from. I don't know how it works in Vue though.

### CODE REVIEW

**Comment by Juhlinus** [comment]
Hello @antonnyman !

Thanks for your PR, but if import the InertiaApp in your bootstrap file, then this shouldn't be needed.

Read the documentation for client side setup, [found here](https://inertiajs.com/client-side-setup).

**Comment by antonnyman** [comment]
Ok!
I guess I must have set my project up wrong then, because if I don't specify the imports then I get `Uncaught ReferenceError: InertiaLink is not defined`. I need to import React as well.

Example repo: https://github.com/antonnyman/inertia-import-react-example
Javascript code is in: `app/javascript/packs/` and `app/javascript/pages/`

**Comment by Juhlinus** [comment]
Yeah, it looks like you've set it up correctly. I don't have any experience with React and Svelte myself. 

Looking through some React code it seems that you are actually correct. When using VueJS(like I am) then this is not needed, so that is part of the confusion.

In regards as to your PR, maybe there's a better way to express that the import is needed instead of including it in each snippet?

**Comment by antonnyman** [comment]
And I was equally confused when I didn't see any imports, because I don't know Vue. 🙂 

I'd say it's pretty common to include how to import a React component (named/default export, etc) in code, but I can definetely add a comment on why.

**Comment by Juhlinus** [comment]
> And I was equally confused when I didn't see any imports, because I don't know Vue. 🙂
> 
> I'd say it's pretty common to include how to import a React component (named/default export, etc) in code, but I can definetely add a comment on why.

Yeah, I was thinking of maybe writing it somewhere else in the documentation. For example the client-side setup.

> Note that for Svelte and React you need to import components like InertiaLink to use them.

Something like this.

**Comment by antonnyman** [comment]
Sure I can include that!

**Comment by sebastiandedeyne** [comment]
I'm not sure if I agree with the current state of the React examples. Like J says, I'd expect React users to be able to assume this.

If you'd really like to make this React-beginner friendly and add the imports, then the examples should be extended to _fully valid_ examples, because the ones in this PR aren't real snippets either.

So my vote is to either keep:

```jsx
<InertiaLink href="/">Home</InertiaLink>
```

Or expand it to a full example:

```jsx
import { InertiaLink } from '@inertiajs/inertia-react'

function Navigation() {
  return <InertiaLink href="/">Home</InertiaLink>
}
```

**Comment by antonnyman** [comment]
@sebastiandedeyne There's no way of knowing if the library authors exported the component as a named export or default export without looking at the docs or source.

For example:
```javascript
//Named
import { InertiaLink, AnotherInertiaComponent } from '@inertiajs/inertia-react'
// Default
import InertiaLink from '@inertiajs/inertia-react/InertiaLink'
import AnotherInertiaComponent from '@inertiajs/inertia-react/AnotherInertiaComponent
```
But I agree that fully functional examples are much better than the ones I provided. I can do the React and Svelte ones, but I probably need help with the Vue example. 🙂

**Comment by antonnyman** [comment]
I've added the comments that @sebastiandedeyne suggested.
If you feel that I should add or change something, I'd be happy to. 

If you think this is the wrong direction to go, please close this PR.

**Comment by BrandonShar** [comment]
FWIW, I agree with specifying the import in the docs (though I don't think it needs to be a full syntactically correct example). 

I agree with @antonnyman that there really isn't a standard for how react libraries provide their code so having that information readily available will help new users get going quicker.

**Pull request closed without merging**
